name: crates_api
description: Simple Dart package to access the crates.io api.
version: 1.0.0
repository: https://github.com/a-K-O-R-A/crates_api

# homepage: https://www.example.com

environment:
  sdk: ">=2.18.4 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

dependencies:
  http: ^0.13.5
  json_annotation: ^4.7.0
